---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 150
  fixme:
    enabled: true
  radon:
    enabled: true
    threshold: "C"

ratings:
  paths:
  - "**.py"

exclude_paths:
- tests/
